import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/store/Provider';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
// import Script from 'next/script';
import AuthInit from '@/components/AuthInit';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'My Gadget',
  description: 'Generated by My Gadget',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col dark`}
      >
        <ReduxProvider>
          <AuthInit>
            <Navbar />

            <main className="grow">{children}</main>

            <Toaster
              position="bottom-right"
              reverseOrder={true}
              toastOptions={{
                duration: 4000,
                className: 'neural-toast-animation',
                style: {
                  background: 'rgba(17, 17, 17, 0.9)',
                  backdropFilter: 'blur(8px)',
                  color: 'var(--color-primary, #29fc56)',
                  border: '1px solid var(--color-primary, #29fc56)',
                  fontSize: '12px',
                  textTransform: 'uppercase',
                  fontWeight: '900',
                  letterSpacing: '0.1em',
                  padding: '16px 24px',
                  borderRadius: '12px',
                  boxShadow: '0 10px 30px rgba(41, 252, 86, 0.15)',
                },
                success: {
                  iconTheme: {
                    primary: 'var(--color-primary, #29fc56)',
                    secondary: '#111',
                  },
                },
              }}
            />

            {/* Crisp Chat – Client-only safe injection */}
            {/* <Script
              id="crisp-chat"
              strategy="afterInteractive"
              dangerouslySetInnerHTML={{
                __html: `
      window.$crisp = [];
      window.CRISP_WEBSITE_ID = "33f66088-4450-4ed2-b515-97244996f25e";

      // গ্রিন কালার সেট করার কমান্ড
      window.$crisp.push(["set", "theme:color", ["#29fc56"]]);

      (function () {
        var d = document;
        var s = d.createElement("script");
        s.src = "https://client.crisp.chat/l.js";
        s.async = 1;
        d.head.appendChild(s);
      })();
    `,
              }}
            /> */}

            <Footer />
          </AuthInit>
        </ReduxProvider>
      </body>
    </html>
  );
}
