import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/store/Provider';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import AuthInit from '@/components/AuthInit';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Gadget BDS',
  description: 'Generated by Gadget BDS',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col light`}
      >
        <ReduxProvider>
          <AuthInit>
            <Navbar />
            <main className="grow">{children}</main>
            <Footer />
          </AuthInit>
        </ReduxProvider>
      </body>
    </html>
  );
}
